spi: fix calls to error helper when building without 32-bit mode support
Commit 56755acc7847d6096e824d0a8270f820176be320 introduced support for
32-bit extra flags. However, when compiling with a toolchain without
support for the extra flags, the following error appears:

  src/spi.c:322:5: error: too few arguments to function '_spi_error'
     return _spi_error(spi, SPI_ERROR_UNSUPPORTED, "Kernel version does not support 32-bit SPI mode flags");

This can be fixed by passing a third argument of 0.

Signed-off-by: Ryan Barnett <ryanbarnett3@gmail.com>
Signed-off-by: Vanya A. Sergeev <v@sergeev.io>