src/spi: fix compiler errors when 32-bit SPI flags aren't supported
Commit 56755acc7847d6096e824d0a8270f820176be320 introduced support for
32-bit extra flags. However, when compiling with a toolchain without
support for the extra flags, the following error appears:

  src/spi.c:322:5: error: too few arguments to function '_spi_error'
     return _spi_error(spi, SPI_ERROR_UNSUPPORTED, "Kernel version does not support 32-bit SPI mode flags");

This can be fixed by passing a third argument of 0.

Along with the error the following warnings appear and are fixed:

  src/spi.c:75:14: warning: unused variable 'data32' [-Wunused-variable]
     uint32_t data32;

  src/spi.c:237:49: warning: unused parameter 'extra_flags' [-Wunused-parameter]
     int spi_get_extra_flags32(spi_t *spi, uint32_t *extra_flags) {

Fix these warnings to allow for clean build.

Signed-off-by: Ryan Barnett <ryanbarnett3@gmail.com>