Add missing header for musl compatibility
<linux/ioctl.h> is needed to get the definition of _IOC_SIZEBITS and
solve the following build failure:

src/spi.c: In function 'spi_transfer':
src/spi.c:100:24: error: '_IOC_SIZEBITS' undeclared (first use in this function)
     if (ioctl(spi->fd, SPI_IOC_MESSAGE(1), &spi_xfer) < 1)

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>